### ISSUE TITLE
ticketid和screenid应该如何配置？

### ISSUE THREAD

**Issue by wode233** [KawaiiSh1zuku/BilibiliWorldRushScript#1]
纯小白请问下如何自定义购买日期和票种，不太明白怎么配置ticket_id = 0和screen_id = 0

**Comment by KawaiiSh1zuku** [comment]
放着不动 动了也没用

**Comment by KawaiiSh1zuku** [comment]
自定义日期和票种就在前面的kind和day 将网页显示的内容复制进去就行了
kind中在网页上显示为￥价格（名字） 只需要名字

**Comment by wode233** [comment]
谢谢，另外还想咨询两个问题，运行途中偶尔弹出Error1，不知是否影响购票
![image](https://github.com/KawaiiSh1zuku/BilibiliWorldRushScript/assets/47889425/fe64ebab-df4b-4c79-8cf7-bdee76e85123)
此外脚本貌似挂个十分钟左右就会闪退，是cookie过期的意思吗？

**Comment by scz0414** [comment]
> 谢谢，另外还想咨询两个问题，运行途中偶尔弹出Error1，不知是否影响购票 ![image](https://user-images.githubusercontent.com/47889425/253487414-fe64ebab-df4b-4c79-8cf7-bdee76e85123.png) 此外脚本貌似挂个十分钟左右就会闪退，是cookie过期的意思吗？

我也遇到同样的问题
2023-07-14 13:58:19没货
2023-07-14 13:58:20没货
检测Cookie是否有效
Traceback (most recent call last):
  File "C:\birth\BilibiliWorldRushScript\main.py", line 161, in <module>
    if check_cookie() == False:
       ^^^^^^^^^^^^^^
  File "C:\birth\BilibiliWorldRushScript\main.py", line 150, in check_cookie
    tg_notify(1)
    ^^^^^^^^^
NameError: name 'tg_notify' is not defined 
想问下正常抢到票会是什么显示和流程

**Comment by KawaiiSh1zuku** [comment]
> 

是cookie过期了 正常抢到票会弹出二维码 打印付款链接

**Comment by KawaiiSh1zuku** [comment]
> 谢谢，另外还想咨询两个问题，运行途中偶尔弹出Error1，不知是否影响购票 ![image](https://user-images.githubusercontent.com/47889425/253487414-fe64ebab-df4b-4c79-8cf7-bdee76e85123.png) 此外脚本貌似挂个十分钟左右就会闪退，是cookie过期的意思吗？

是cookie过期了 正常抢到票会弹出二维码 打印付款链接

**Comment by KawaiiSh1zuku** [comment]
> > 谢谢，另外还想咨询两个问题，运行途中偶尔弹出Error1，不知是否影响购票 ![image](https://user-images.githubusercontent.com/47889425/253487414-fe64ebab-df4b-4c79-8cf7-bdee76e85123.png) 此外脚本貌似挂个十分钟左右就会闪退，是cookie过期的意思吗？
> 
> 我也遇到同样的问题 2023-07-14 13:58:19没货 2023-07-14 13:58:20没货 检测Cookie是否有效 Traceback (most recent call last): File "C:\birth\BilibiliWorldRushScript\main.py", line 161, in if check_cookie() == False: ^^^^^^^^^^^^^^ File "C:\birth\BilibiliWorldRushScript\main.py", line 150, in check_cookie tg_notify(1) ^^^^^^^^^ NameError: name 'tg_notify' is not defined 想问下正常抢到票会是什么显示和流程

是cookie过期了 正常抢到票会弹出二维码 打印付款链接
