### ISSUE TITLE
create()返回验证已超时

### ISSUE THREAD

**Issue by shenidme** [KawaiiSh1zuku/BilibiliWorldRushScript#3]
是因为会员购那边有验证码检查吗？
{'errno': 100051, 'errtag': 0, 'msg': '验证已超时，请重新验证', 'data': {}}

**Comment by KawaiiSh1zuku** [comment]
是的 不知道什么时候+的验证

**Comment by shenidme** [comment]
感谢大佬的脚本，但是下午才看到，已经结束咧😭
